### ISSUE TITLE
precedentDocument Extension should point to Bundle.identifer

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-orf#10]
precedentDocument Extension should point to Bundle.identifer, not to Composition.identifier

order.precedentDocumentId -> change to order.precedentDocumentIdentifier

**Comment by ziegm** [comment]
**Date, the document was created**

The date the document was created is currently defined as Composition.date. 
Would it make sense to define it as Bundle.datetime because the identifier of the document has now changed to Bundle.identifier?
