### ISSUE TITLE
Profile (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-orf#30]
ch.fhir.ig.ch-orf#0.10.0 /

ch-orf/input/fsh/SD_Profiles.fsh: 
section[originalRepresentation].code = LNC#55108-5 "Clinical presentation" => should be one of [Clinical presentation Document, Clinical presentation Doc]

Marcel Hanselmann

**Comment by lpg-tech** [comment]
yes, ok
