### ISSUE TITLE
ServiceRequest.performer

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-orf#5]
Feedback aus ch-lab-order, marcel hanselmann:

Ich bekomme bei den ServiceRequest Beispielen folgenden Fehler:

ServiceRequest/3-gyn: ServiceRequest.performer[0] (l44/c14) | error | Es konnte kein passendes Profil für Organization/LaborPipette (nach Typ) unter den Auswahlmöglichkeiten [; [CanonicalType[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitioner], CanonicalType[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitionerrole]]] gefunden werden
-- | -- | --
ServiceRequest/3-gyn: ServiceRequest.performer[0] (l44/c14) | error | Ungültiger Ressourcen-Zieltyp. Gefunden Organization, aber einen von ([Practitioner, PractitionerRole]) erwartet

Ich bin der Meinung, dass das ORF Profil die Organization als ServiceRequest.performer zulassen müsste, der Laborauftrag geht schliesslich an ein Labor, und nicht an den Laborarzt persönlich.

**Comment by oliveregger** [comment]
related to https://github.com/ehealthsuisse/ch-orf/issues/4?

**Comment by ziegm** [comment]
Der ServiceRequest.performer wird nun als PractitionerRole abgebildet. Aus der PractitionerRole können dann Practitioner (0..1) und/oder Organization (0..1) referenziert werden.
